# Generated by Django 2.1.1 on 2018-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexagon',
            name='heat',
            field=models.IntegerField(default=0),
        ),
    ]
