# Generated by Django 2.1.1 on 2018-09-28 15:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0002_hexagon_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='incident',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.IntegerField(null=True),
        ),
    ]
